services:
  gluetun-vpn:
    image: qmcgaw/gluetun
    container_name: gluetun-vpn
    cap_add:
      - NET_ADMIN
    volumes:
      - gluetun-config:/gluetun # Persistent configuration storage for Gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn # VPN provider
      - VPN_TYPE=wireguard # Use WireGuard or OpenVPN
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY} # Your WireGuard private key (set in .env)
      - WIREGUARD_ADDRESS=${WIREGUARD_ADDRESS} # VPN address (set in .env)
      - SERVER_CITIES=${SERVER_CITIES} # VPN server city or country (set in .env)
      - PUID=${PUID} # User ID (set in .env)
      - PGID=${PGID} # Group ID (set in .env)
      - TZ=${TZ} # Timezone (set in .env)
      - UPDATER_PERIOD=24h # Automatically update every 24 hours
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1 # Enable IP forwarding for routing
    restart: unless-stopped
    networks:
      - vpn_network

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID} # User ID (set in .env)
      - PGID=${PGID} # Group ID (set in .env)
      - TZ=${TZ} # Timezone (set in .env)
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config # Configuration storage for qBittorrent
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - vpn_network
    depends_on:
      - gluetun-vpn
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID} # User ID (set in .env)
      - PGID=${PGID} # Group ID (set in .env)
      - TZ=${TZ} # Timezone (set in .env)
    volumes:
      - sonarr-config:/config # Configuration storage for Sonarr
    ports:
      - 8989:8989
    networks:
      - vpn_network
    depends_on:
      - gluetun-vpn
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID} # User ID (set in .env)
      - PGID=${PGID} # Group ID (set in .env)
      - TZ=${TZ} # Timezone (set in .env)
    volumes:
      - radarr-config:/config # Configuration storage for Radarr
    ports:
      - 7878:7878
    networks:
      - vpn_network
    depends_on:
      - gluetun-vpn
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    networks:
      - vpn_network
    depends_on:
      - gluetun-vpn
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID} # User ID (set in .env)
      - PGID=${PGID} # Group ID (set in .env)
      - TZ=${TZ} # Timezone (set in .env)
    volumes:
      - prowlarr-config:/config # Configuration storage for Prowlarr
    ports:
      - 9696:9696
    networks:
      - vpn_network
    depends_on:
      - gluetun-vpn
    restart: unless-stopped

networks:
  vpn_network:
    driver: bridge # Use bridge networking to isolate the VPN network

volumes:
  gluetun-config: # Persistent storage for Gluetun configuration
  qbittorrent-config: # Persistent storage for qBittorrent configuration
  sonarr-config: # Persistent storage for Sonarr configuration
  radarr-config: # Persistent storage for Radarr configuration
  prowlarr-config: # Persistent storage for Prowlarr configuration
