version: "3.8" # Specify Docker Compose file format version

services:
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    ports:
      - 5454:5454
    volumes:
      - notifiarr-config:/config # Persist Notifiarr configuration data
    environment:
      - PUID=${PUID} # User ID (set in .env file)
      - PGID=${PGID} # Group ID (set in .env file)
    network_mode: host

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     environment:
      - WATCHTOWER_CLEANUP=true # Optional: Automatically clean up old images
      - WATCHTOWER_LABEL_ENABLE=true 
      - WATCHTOWER_POLL_INTERVAL=3600 # Check every hour (3600 seconds)
    restart: unless-stopped
