version: "3.8" # Specify Docker Compose file format version

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID} # User ID (set in .env file)
      - PGID=${PGID} # Group ID (set in .env file)
      - VERSION=docker
      - TZ=${TZ} # Timezone (set in .env file)
      - NVIDIA_VISIBLE_DEVICES=all # Use all NVIDIA devices for GPU acceleration
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility # NVIDIA driver capabilities
    volumes:
      - plex-config:/config # Persist Plex configuration data
      - /path/to/tvseries:/tv # Path to the tv shows directory
      - /path/to/movies:/movies # Path to the movies directory
    devices:
      - /dev/dri:/dev/dri # Hardware acceleration device for transcoding
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    network_mode: host
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID} # User ID (set in .env file)
      - PGID=${PGID} # Group ID (set in .env file)
      - TZ=${TZ} # Timezone (set in .env file)
    volumes:
      - tautulli-config:/config # Persist Tautulli configuration data
    ports:
      - 8181:8181/tcp
    network_mode: host
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - TZ=${TZ} # Timezone (set in .env file)
      - PUID=${PUID} # User ID (set in .env file)
      - PGID=${PGID} # Group ID (set in .env file)
    volumes:
      - overseerr-config:/config # Persist Overseerr configuration data
    ports:
      - 5055:5055
    network_mode: host
    restart: unless-stopped

    tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    environment:
      - PUID=${PUID} # User ID (set in .env file)
      - PGID=${PGID} # Group ID (set in .env file)
      - TZ=${TZ} # Timezone (set in .env file)
    volumes:
      - tdarr-config:/app/configs # Persist Tdarr configuration data
      - /path/to/media:/media # Path to media files
    ports:
      - 8265:8265 
      - 8266:8266 
    restart: unless-stopped
    network_mode: host

volumes:
  plex-config:
  tautulli-config:
  overseerr-config:
  notifiarr-config:
  tdarr-config:
